name: CI - DevOps Lab AWS (mínimo)

on:
  push:
    branches: ['**']        # roda em qualquer branch
  pull_request:
    branches: ['main']      # roda em PRs direcionados para main

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no DockerHub
        run: echo "${{ secrets.dckr_pat_6J4GOMU794M5DIhJ6m-HSMfVZC0 }}" | docker login -u "${{ secrets.nessao }}" --password-stdin

      - name: Build da imagem Docker
        run: docker build -t ${{ secrets.nessao }}/devops-lab-api:latest ./app

      - name: Push para DockerHub
        run: docker push ${{ secrets.nessao }}/devops-lab-api:latest
